const arrayProducts = [
    {"id":1,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/truemade_fsh53f.jpg","nombre":"TrueMade Whey Protein","precio":5624,"sabor":"Chocolate","cat":"Proteina", "descripcion": "Aquí vá la descripción del producto, lo pondré más adelante porque me atrasé un poco con la segunda pre-entreda del proyecto."},
    {"id":2,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331327/imagenes%20ThikiaSport/wheyXpro_wr0cfz.jpg","nombre":"Whey Xpro","precio":4724,"sabor":"Vainilla","cat":"Proteina",  "descripcion": "Aquí vá la descripción del producto, lo pondré más adelante porque me atrasé un poco con la segunda pre-entreda del proyecto."},
    {"id":3,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/ultraMass_kt5qhk.jpg","nombre":"Ultra Mass","precio":4049,"sabor":"Cookies","cat":"Proteina",  "descripcion": "Aquí vá la descripción del producto, lo pondré más adelante porque me atrasé un poco con la segunda pre-entreda del proyecto."},
    {"id":4,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/plantProtein_mhynqe.jpg","nombre":"Plant Protein","precio":2940,"sabor":"Sin sabor","cat":"Proteina",  "descripcion": "Aquí vá la descripción del producto, lo pondré más adelante porque me atrasé un poco con la segunda pre-entreda del proyecto."},
    {"id":5,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331325/imagenes%20ThikiaSport/100WheyChoco_unqagr.jpg","nombre":"100% Whey Protein","precio":4274,"sabor":"Banana","cat":"Proteina",  "descripcion": "Aquí vá la descripción del producto, lo pondré más adelante porque me atrasé un poco con la segunda pre-entreda del proyecto."},
    {"id":6,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/prewar_jehpn3.png","nombre":"Pre War","precio":3915,"sabor":"Fuit Punch","cat":"Aimnoacido",  "descripcion": "Aquí vá la descripción del producto, lo pondré más adelante porque me atrasé un poco con la segunda pre-entreda del proyecto."},
    {"id":7,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/muscleMax_qylqjo.jpg","nombre":"Muscle Max","precio":1469,"sabor":"Sin sabor","cat":"Aimnoacido",  "descripcion": "Aquí vá la descripción del producto, lo pondré más adelante porque me atrasé un poco con la segunda pre-entreda del proyecto."},
    {"id":8,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/reload_gv1d23.png","nombre":"Re Load","precio":2376,"sabor":"Lemonade","cat":"Aimnoacido",  "descripcion": "Aquí vá la descripción del producto, lo pondré más adelante porque me atrasé un poco con la segunda pre-entreda del proyecto."},
    {"id":9,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331325/imagenes%20ThikiaSport/bcaa_atp8wp.png","nombre":"BCAA 12:1:1","precio":2520,"sabor":"Sin sabor","cat":"Aimnoacido",  "descripcion": "Aquí vá la descripción del producto, lo pondré más adelante porque me atrasé un poco con la segunda pre-entreda del proyecto."},
    {"id":10,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331325/imagenes%20ThikiaSport/amino_gi7wld.png","nombre":"Amino 4500","precio":3009,"sabor":"Sin sabor","cat":"Aimnoacido",  "descripcion": "Aquí vá la descripción del producto, lo pondré más adelante porque me atrasé un poco con la segunda pre-entreda del proyecto."},
    {"id":11,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/oxidonitrico_oxhrfu.png","nombre":"Óxido Nítrico","precio":2231,"sabor":"Sin sabor","cat":"Aimnoacido",  "descripcion": "Aquí vá la descripción del producto, lo pondré más adelante porque me atrasé un poco con la segunda pre-entreda del proyecto."},
    {"id":12,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/shakerENA_vh1vtg.png","nombre":"Shaker ENA","precio":949,"sabor":"'-'","cat":"Shaker",  "descripcion": "Aquí vá la descripción del producto, lo pondré más adelante porque me atrasé un poco con la segunda pre-entreda del proyecto."},
    {"id":13,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/shakerPlus_kyet9x.png","nombre":"Shaker PLUS","precio":1100,"sabor":"'-'","cat":"Shaker",  "descripcion": "Aquí vá la descripción del producto, lo pondré más adelante porque me atrasé un poco con la segunda pre-entreda del proyecto."},
    {"id":14,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/shakerPremiun_hgayli.png","nombre":"Shaker Premiun","precio":2640,"sabor":"'-'","cat":"Shaker",  "descripcion": "Aquí vá la descripción del producto, lo pondré más adelante porque me atrasé un poco con la segunda pre-entreda del proyecto."}
]

export default arrayProducts