const arrayProducts = [
    {"id":1,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/truemade_fsh53f.jpg","nombre":"TrueMade Whey Protein","precio":5624,"sabor":"Chocolate","cat":"Proteina", "discount":15, "initialPrice":6467.6,"descripcion": "Este tipo de suplemento ayuda a complementar la alimentación de personas con objetivos o requerimientos nutricionales específicos. Su consumo puede ser indicado por diversos factores, como la duración y la intensidad de la actividad física, el tipo de deporte, el ambiente en el que se practica, la edad, la composición corporal, el peso, entre otros. Es importante resaltar que su uso debe estar acompañado por una alimentación equilibrada y hábitos de vida saludable.", "stock": 22},
    {"id":2,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331327/imagenes%20ThikiaSport/wheyXpro_wr0cfz.jpg","nombre":"Whey Xpro","precio":4724,"sabor":"Vainilla","cat":"Proteina", "discount": 20, "initialPrice":5668.8,"descripcion": "Whey X Pro Complex Protein aporta una combinación explosiva de proteínas, creatina, taurina, glutamina, aminoácidos, vitaminas, minerales y antioxidantes, en una nueva fórmula mejorada. Aporta más sabor y una máxima disolución para lograr mejores resultados y la podés consumir antes o después del entrenamiento. Es la proteína de suero más avanzada del mercado.", "stock": 15},
    {"id":3,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/ultraMass_kt5qhk.jpg","nombre":"Ultra Mass","precio":4049,"sabor":"Cookies","cat":"Proteina",  "descripcion": "Ultra Mass es un alimento natural a base de proteínas de alto valor biológico, carbohidratos, vitaminas, minerales, lipolíticos y grasas esenciales. Aumentar el tamaño de la masa muscular requiere del balance entre un entrenamiento duro y una nutrición de calidad.", "stock": 28},
    {"id":4,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/plantProtein_mhynqe.jpg","nombre":"Plant Protein","precio":2940,"sabor":"Sin sabor","cat":"Proteina",  "descripcion": "Proteína Vegetal de máxima calidad, elaborada a base de proteína de arvejas. Ideal para quienes eligen una alimentación vegana o vegetariana o para complementar cualquier dieta con deficiencia proteica.", "stock": 15},
    {"id":5,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331325/imagenes%20ThikiaSport/100WheyChoco_unqagr.jpg","nombre":"100% Whey Protein","precio":4274,"sabor":"Banana","cat":"Proteina",  "descripcion": "La suplementación con proteínas de suero (Whey protein) es ideal para complementar tus desayunos, tus meriendas y tu snack recovery post entreno. Los 20 gs de proteínas por porción de 100% WHEY la posicionan como una gran opción para toda la población fisicamente activa, tanto hombres como mujeres. La calidad de 100% WHEY es ideal para favorecer la síntesis de masa muscular, ya que es rica en aminoácidos ramificados conocidos como BCAA.", "stock": 9},
    {"id":6,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/prewar_jehpn3.png","nombre":"Pre War","precio":3915,"sabor":"Fuit Punch","cat":"Aimnoacido", "discount": 25, "initialPrice":4893.75,"descripcion": "PRE WAR es la siguiente evolución en pre entrenamientos. Diseñado con precisión para desafiar tus límites, favorece la concentración, el aumento de energía, la fuerza, el tamaño muscular y la recuperación. Entrena con nuestro Pre work más completo y con fórmula mejorada con 200mg de cafeína por ingesta.", "stock": 20},
    {"id":7,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/muscleMax_qylqjo.jpg","nombre":"Muscle Max","precio":1469,"sabor":"Sin sabor","cat":"Aimnoacido",  "descripcion": "MUSCLE MAX favorece el crecimiento de los tejidos y músculos, el metabolismo del exceso de grasa, la reparación del sistema inmunológico y actúa como detoxificante.", "stock": 19},
    {"id":8,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/reload_gv1d23.png","nombre":"Re Load","precio":2376,"sabor":"Lemonade","cat":"Aimnoacido",  "descripcion": "RELOAD es lo último en post entrenamiento. Ideal para después de un entrenamiento intenso. Te traemos el mejor ratio de BCAA (2:1:1) con la cantidad exacta que necesitas para recuperarte más rápido y volver nuevamente al juego.", "stock": 11},
    {"id":9,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331325/imagenes%20ThikiaSport/bcaa_atp8wp.png","nombre":"BCAA 12:1:1","precio":2520,"sabor":"Sin sabor","cat":"Aimnoacido",  "descripcion": "Diseñado para personas que realizan actividad física intensa, ya que colabora con la construcción, reparación y mantenimiento de los músculos. BCAA 12:1.1 es un excelente recuperador, elaborado con un súper ratio de aminoácidos ramificados, aportando 1800 mg de L-Leucina por porción, que mejoran el desarrollo muscular y disminuyen la degradación de proteínas durante los ejercicios.", "stock": 11},
    {"id":10,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331325/imagenes%20ThikiaSport/amino_gi7wld.png","nombre":"Amino 4500","precio":3009,"sabor":"Sin sabor","cat":"Aimnoacido", "discount": 22 , "initialPrice":3670.98,"descripcion": "Favorece el crecimiento y la recuperación muscular post work. Es la perfecta mezcla de aminoácidos para ayudar a aquellos que quieren entrenar más fuerte y recuperarse más rápido. Usado después del entrenamiento, acelera la recuperación y maximiza el crecimiento muscular. Formulado con ingredientes de alta calidad, ayuda a todos los atletas a volverse fuertes, mantenerse saludables y en forma.", "stock": 13},
    {"id":11,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/oxidonitrico_oxhrfu.png","nombre":"Óxido Nítrico","precio":2231,"sabor":"Sin sabor","cat":"Aimnoacido",  "descripcion": "El óxido nítrico es un compuesto muy importante para la fisiología de nuestro organismo. Actúa como vasodilatador haciendo que la sangre circule a mayor velocidad, aumentando así el aporte de oxígeno y de nutrientes a los músculos. Esto permite mejorar el rendimiento durante el entrenamiento, la recuperación del músculo y el aumento de su capacidad de crecimiento.", "stock": 21},
    {"id":12,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/shakerENA_vh1vtg.png","nombre":"Shaker ENA","precio":949,"cat":"Shaker",  "descripcion": "Ayuda a romper las partículas de polvo. Es ideal para aquellos productos en polvo que requieran una disolución excelente, tanto en agua como en leche. El Vaso Batidor presenta en su interior un aro en forma de estrella que rompe las partículas de polvo disolviéndolas con el batido. Con nuestro exclusivo vaso shaker, mezclar incluso las más espesas de las proteínas es facilísimo.", "stock": 7},
    {"id":13,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/shakerPlus_kyet9x.png","nombre":"Shaker PLUS","precio":1100,"cat":"Shaker",  "descripcion": "Es ideal para aquellos productos en polvo que requieran una disolución excelente, tanto en agua como en leche. El Vaso Batidor presenta en su interior un aro en forma de estrella que rompe las partículas de polvo disolviéndolas con el batido. Con nuestro exclusivo vaso shaker, mezclar incluso las más espesas de las proteínas es facilísimo. Tiene incluido un compartimiento para las proteínas y un pastillero.", "stock": 16},
    {"id":14,"imagen":"https://res.cloudinary.com/dyzoubfmd/image/upload/v1670331326/imagenes%20ThikiaSport/shakerPremiun_hgayli.png","nombre":"Shaker Premiun","precio":2640,"cat":"Shaker", "discount": 30 , "initialPrice":3432, "descripcion": "Nuevo modelo con tapa a rosca y resorte mezclador. Ideal para llevar tu propia bebida, o suplementos en polvo que quieras diluir fácilmente y sin grumos, ya que trae un batidor de acero inoxidable pulido oval para facilitar el batido y su limpieza. Ayuda a romper las partículas de polvo. Es ideal para aquellos productos que requieran una disolución excelente, tanto en agua como en leche. Seguro para lavavajillas, microondas y freezer. ", "stock": 15}
]

export default arrayProducts